apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bgd
    app.kubernetes.io/instance: bdg
  name: bgd
  namespace: bdg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bgd
    spec:
      containers:
        - env:
            - name: COLOR
              value: blue
          image: 'quay.io/redhatworkshops/bgd:latest'
          name: bgd
          resources: {}
